Repository CSSSR/lorem-scriptum, pull requests merged in 2022-04, with the labels that each got.

#1 fix: LS-107: fix reviews link
  src/includes/reviews.njk
Labels: Test OK

#5 fix: LS-108: changes position of the banner cookie
  src/data/cookieBanner.json
  src/includes/cookieBanner.njk
  src/styles/blocks/cookieBanner.css
Labels: Test OK

#3 fix: LS-99: fix meta
  src/layouts/page.njk
  src/pages/index.njk
Labels: Reopened

#8 fix: LS-110: replaces favicon set
  src/assets/favicon.png
  src/assets/favicon.svg
  src/assets/favicons/apple-touch-icon.png
  src/assets/favicons/favicon-16x16.png
  src/assets/favicons/favicon-32x32.png
  src/assets/favicons/favicon.ico
  src/assets/favicons/safari-pinned-tab.svg
  src/layouts/page.njk
Labels: Test OK

#11 fix: LS-118: fixes sending form data to safari
  src/layouts/page.njk
  src/scripts/scripts.js
Labels: Test OK

#13 feat: LS-112: shifted to mobile costs
  src/styles/blocks/exampleProject.css
Labels: Test OK

#10 fix: LS-104: fixes styles in sections
  src/data/footer.json
  src/includes/footer.njk
  src/styles/blocks/applicationForm.css
  src/styles/blocks/employeeContacts.css
  src/styles/blocks/features.css
  src/styles/blocks/link.css
  src/styles/blocks/ourServices.css
Labels: Test OK

#16 feat: LS-126: change footer
  src/data/footer.json
  src/includes/footer.njk
  src/styles/blocks/footer.css
Labels: Test OK

#14 fix: LS-95: makes fixes for safari 13
  src/assets/Hellen-Perezhogina.png
  src/assets/employeeContacts/golovin.webp
  src/assets/employeeContacts/golovin2x.png
  src/assets/employeeContacts/golovin2x.webp
  src/assets/employeeContacts/sekirkin.webp
  src/assets/employeeContacts/sekirkin2x.png
  src/assets/employeeContacts/sekirkin2x.webp
  src/assets/reviews/esther-tan.webp
  src/assets/reviews/esther-tan2x.jpg
  src/assets/reviews/esther-tan2x.webp
  src/data/applicationForm.json
  src/data/employeeContacts.json
  src/data/reviews.json
  src/includes/applicationForm.njk
  src/includes/employeeContacts.njk
  src/includes/ourServices.njk
  src/includes/reviews.njk
  src/styles/blocks/ourServices.css
Labels: RFT

#17 feat: LS-121: fonts refactoring
  src/styles/blocks/applicationForm.css
  src/styles/blocks/button.css
  src/styles/blocks/cookieBanner.css
  src/styles/blocks/employeeContacts.css
  src/styles/blocks/exampleProject.css
  src/styles/blocks/features.css
  src/styles/blocks/footer.css
  src/styles/blocks/header.css
  src/styles/blocks/input.css
  src/styles/blocks/mainPage.css
  src/styles/blocks/ourServices.css
  src/styles/blocks/reviews.css
  src/styles/blocks/techStack.css
  src/styles/scaffolding/base.css
  src/styles/scaffolding/variables.css
Labels: RFT
